import { jsPDF } from "jspdf";

export function downloadATSReport(data) {
  const doc = new jsPDF();

  const {
    filename = "Resume.pdf",
    ats_score = 0,
    overall_rating = "N/A",
    strengths = [],
    missing_skills = [],
    suggestions = [],
    recommended_roles = [],
  } = data;

  let y = 20;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.text("CareerPilot AI", 20, y);

  y += 10;
  doc.setFontSize(16);
  doc.text("AI Resume Analysis Report", 20, y);

  y += 15;

  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");

  doc.text(`Resume: ${filename}`, 20, y);
  y += 8;

  doc.text(
    `Generated: ${new Date().toLocaleString()}`,
    20,
    y
  );

  y += 15;

  doc.setFont("helvetica", "bold");
  doc.text("ATS Score", 20, y);

  y += 8;

  doc.setFont("helvetica", "normal");
  doc.text(`${ats_score}%`, 20, y);

  y += 8;
  doc.text(`Overall Rating: ${overall_rating}`, 20, y);

  y += 15;

  doc.setFont("helvetica", "bold");
  doc.text("Strengths", 20, y);

  y += 8;

  doc.setFont("helvetica", "normal");

  strengths.forEach((item) => {
    doc.text(`• ${item}`, 25, y);
    y += 7;
  });

  y += 5;

  doc.setFont("helvetica", "bold");
  doc.text("Missing Skills", 20, y);

  y += 8;

  doc.setFont("helvetica", "normal");

  missing_skills.forEach((item) => {
    doc.text(`• ${item}`, 25, y);
    y += 7;
  });

  y += 5;

  doc.setFont("helvetica", "bold");
  doc.text("AI Suggestions", 20, y);

  y += 8;

  doc.setFont("helvetica", "normal");

  suggestions.forEach((item, index) => {
    doc.text(`${index + 1}. ${item}`, 25, y);
    y += 7;
  });

  y += 5;

  doc.setFont("helvetica", "bold");
  doc.text("Recommended Roles", 20, y);

  y += 8;

  doc.setFont("helvetica", "normal");

  recommended_roles.forEach((item) => {
    doc.text(`• ${item}`, 25, y);
    y += 7;
  });

  y += 15;

  doc.setFontSize(10);
  doc.text(
    "Generated by CareerPilot AI",
    20,
    y
  );

  doc.save("CareerPilot_AI_ATS_Report.pdf");
}
export function downloadCoverLetterPDF({
  coverLetter = "",
  candidateName = "Candidate",
  companyName = "Company",
  jobTitle = "Position",
}) {
  if (!coverLetter.trim()) {
    alert("Please generate a cover letter first.");
    return;
  }

  const doc = new jsPDF();

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  const marginLeft = 20;
  const marginRight = 20;
  const maxTextWidth = pageWidth - marginLeft - marginRight;

  let y = 20;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text(candidateName, marginLeft, y);

  y += 10;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.text(`Application for ${jobTitle}`, marginLeft, y);

  y += 7;
  doc.text(companyName, marginLeft, y);

  y += 12;

  doc.setDrawColor(180);
  doc.line(marginLeft, y, pageWidth - marginRight, y);

  y += 12;

  doc.setFontSize(11);

  const paragraphs = coverLetter
    .split(/\n+/)
    .map((paragraph) => paragraph.trim())
    .filter(Boolean);

  paragraphs.forEach((paragraph) => {
    const lines = doc.splitTextToSize(paragraph, maxTextWidth);

    lines.forEach((line) => {
      if (y > pageHeight - 25) {
        doc.addPage();
        y = 20;
      }

      doc.text(line, marginLeft, y);
      y += 6;
    });

    y += 4;
  });

  const totalPages = doc.getNumberOfPages();

  for (let page = 1; page <= totalPages; page += 1) {
    doc.setPage(page);

    doc.setFontSize(9);
    doc.setTextColor(100);

    doc.text(
      `Generated by CareerPilot AI • Page ${page} of ${totalPages}`,
      pageWidth / 2,
      pageHeight - 10,
      { align: "center" }
    );
  }

  const safeJobTitle = jobTitle
    .replace(/[^a-z0-9]/gi, "_")
    .replace(/_+/g, "_");

  doc.save(`CareerPilot_Cover_Letter_${safeJobTitle}.pdf`);
}